### ISSUE TITLE
proposal: add "explanation" field

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#14]
`{% textblock "first name" explanation="used in all forms, bla bla bla, may even be longer than 64 chars..." %}`

using keyword arguments, this would allow to not specify `type` and `show_key` parameters, but only the explanation (and the other way round...). I know of django-classy-tags, to easily make kwargs work for templatetags...

what do you think?

**Comment by benzkji** [comment]
as I can see now (after reading django docs ;-), kwargs are possible with plain django's simple tag as well...if you agree with the proposal, I would go ahead?

**Comment by fabiangermann** [comment]
Sure. Do you plan to just display the value of explanation in the admin? As a help for content creators? In this case help_text would may be a little more in line with other django functionality? Not that it would matter really but I guess it would be easy to remember without documentation because it's so often used in models.

**Comment by benzkji** [comment]
yes, exactly. help_text sounds perfect.

**Comment by fabiangermann** [comment]
I think this has been resolved for some time (I hope). Released with (at latest) 0.7.
