### ISSUE TITLE
create "as" version of the templatetag

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#15]
when one needs the output of the tag for further processing.

    {% textblock "contact_email" as contact_email %}
    {% if contact_email %}
        {% mailprotector_whatever_tag contact_email %}  # creates spam protected email link
    {% endif %}

again, easy "as" tags seem possible with django-classy-tags.

**Comment by fabiangermann** [comment]
Since django-textblocks is intended as a very simple replacement for more complex content management (like CMS Pages for example) I'd rather not introduce additional dependencies. Even more so because from Django 1.9 on this is already possible with simple-Tags (which the textblock-Tag is) and does not require any change at all.

**Comment by benzkji** [comment]
agree. didnt know about that django 1.9 thing, so definitly no classy-tags - very happy with that!
