### ISSUE TITLE
change max_length on key

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#32]
I run into `Data too long for column 'key' at row 1"` every now and then...I then have to write less self explaining keys, that would make a working product without translating anything.

How about 128?

I dont really know about implications concerning the index on db level. Also, the value could be configurable, ... as textblocks needs custom migrations anyway?

**Comment by fabiangermann** [comment]
Initially I thought the cache key length was probably the limiting factor. Memcached only allows up to 250 Bytes (We use redis but nontheless) and since the key technically allows unicode characters the maximum length is very restricted.

But then I remembered that the key is hashed for the cache key so this isn't really a concern (anymore). I raised it to 120 chars for now. I guess too long probably isn't practical and the additional logic required for a settings is probably not worth it.

https://github.com/fabiangermann/django-textblocks/commit/9b8671e7fe3872570fd3b7625e9b1b7d03ab3ca7
