### ISSUE TITLE
question: how to handle textblocks that are not necessarily called in a template

### ISSUE THREAD

**Issue by benzkji** [fabiangermann/django-textblocks#35]
Let's say in if statements, when form checking, or the like...those blocks will not be called and created until someone submits wrong form data?!

Doing it like gettext, ie perform some kind of offline parsing / textblock creation via manage.py would be great...but kind of a bigger work, also I wouldnt now how to approach it.

Do you ever run into this? How did you solve it? (other than just creating blocks manually, which is a pain right now because it must be done directly in the database :| => make `key` (and `help_text`) editable, for new textblocks! )

**Comment by fabiangermann** [comment]
This actually isn't that big of a problem for us I think. Probably because all Textblocks are displayed multiple times while testing.

Although I havent looked into it I guess (too) that a parser like gettext will be quite a bit of work. But admin-form approach would of course be very simple to implement.

**Comment by fabiangermann** [comment]
Setting key/type via admin interface is now possible (I'll extend for help_text when I've merged the PR).

https://github.com/fabiangermann/django-textblocks/commit/6d1055f4a3ab26f4fa1d84ba1ea165906c4c2d73
